#!/bin/bash

# AI ERP System - Automated Installer
# Supported OS: Ubuntu/Debian

set -e # Exit on error

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}   AI ERP System - Installation Utility   ${NC}"
echo -e "${BLUE}========================================${NC}"

# 1. Prerequisite Checks
echo -e "${GREEN}[1/6] Checking System Prerequisites...${NC}"

if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed.${NC}"
    echo "Please install Node.js (v18+) and try again."
    exit 1
fi

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: Python3 is not installed.${NC}"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed.${NC}"
    exit 1
fi

# Install PM2 globally if not present
if ! command -v pm2 &> /dev/null; then
    echo "Installing PM2 globally..."
    npm install -g pm2
fi

echo "System checks passed."

# 2. Project Setup
PROJECT_DIR=$(pwd)
echo -e "${GREEN}[2/6] Setting up Project in: ${PROJECT_DIR}${NC}"

# Create Virtual Environment
if [ ! -d "venv" ]; then
    echo "Creating Python Virtual Environment..."
    python3 -m venv venv
else
    echo "Virtual Environment exists."
fi

# Activate Venv
source venv/bin/activate

# Install Python Dependencies
echo "Installing Backend Dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

# 3. Environment Configuration
echo -e "${GREEN}[3/6] Configuring Environment...${NC}"

if [ ! -f ".env" ]; then
    echo "Creating .env file from template..."
    # Generate a basic .env if missing
    cat > .env <<EOL
# Generated by install.sh
DATABASE_URL=sqlite:///./erp_database.db
SECRET_KEY=$(openssl rand -hex 32)
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
GEMINI_API_KEY=your_gemini_api_key_here
environment=production
EOL
    echo -e "${BLUE}NOTICE: A new .env file has been created. Please edit it with your real API keys.${NC}"
else
    echo ".env file already exists."
fi

# 4. Frontend Setup
echo -e "${GREEN}[4/6] Setting up Frontend...${NC}"
cd frontend

echo "Installing Frontend Dependencies (this may take a while)..."
npm install

echo "Building Frontend for Production..."
npm run build

cd ..

# 5. Database Initialization
echo -e "${GREEN}[5/6] Initializing Database...${NC}"
# Run Alembic migrations if available, or create_schema.py
# Assuming create_schema.py is the safe init method for now
if [ -f "create_financial_schema.py" ]; then
    python3 create_financial_schema.py
fi
# Also run standard schema creation
python3 -c "from app.database import Base, engine; Base.metadata.create_all(bind=engine)" || echo "Database Init Warning: Check logs."

# 6. Process Management (PM2)
echo -e "${GREEN}[6/6] Configuring Process Manager (PM2)...${NC}"

# Generate dynamic ecosystem.config.js to avoid hardcoded paths
cat > ecosystem.config.js <<EOL
module.exports = {
  apps: [
    {
      name: 'erp-backend',
      script: '${PROJECT_DIR}/venv/bin/python3',
      args: '-m uvicorn app.main:app --host 0.0.0.0 --port 8000',
      cwd: '${PROJECT_DIR}',
      env: {
        PORT: 8000,
        PYTHONPATH: "${PROJECT_DIR}"
      }
    },
    {
      name: 'erp-frontend',
      cwd: '${PROJECT_DIR}/frontend',
      script: 'npm',
      args: 'run dev -- --host 0.0.0.0 --port 56000',
      env: {
        PORT: 56000
      }
    }
  ]
};
EOL

# Reload PM2
pm2 delete all || true
pm2 start ecosystem.config.js
pm2 save

echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}   Installation Complete!   ${NC}"
echo -e "${BLUE}========================================${NC}"
echo -e "Backend running on: http://localhost:8000"
echo -e "Frontend running on: http://localhost:56000"
echo -e ""
echo -e "To create an Admin User, run:"
echo -e "  source venv/bin/activate"
echo -e "  python3 fix_admin_user.py"
