"""Add Dynamic Approval System - Partners and Approval Policies

Revision ID: 015d16e81935
Revises: 05897c3b244d
Create Date: 2026-01-24 20:22:35.390028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '015d16e81935'
down_revision: Union[str, Sequence[str], None] = '05897c3b244d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accommodations', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('accommodations', 'visit_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('accommodations', 'details',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Hotel name, address, or guest house details',
               existing_nullable=True)
    op.alter_column('accommodations', 'bed_assigned',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Bed number (1-5) for office guest house',
               existing_nullable=True)
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_type'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_visit_id'), table_name='accommodations')
    op.drop_column('accommodations', 'updated_at')
    op.drop_column('accommodations', 'created_at')
    op.alter_column('itinerary_items', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('itinerary_items', 'visit_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('itinerary_items', 'supplier_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('itinerary_items', 'appointment_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Scheduled appointment time',
               existing_nullable=False)
    op.alter_column('itinerary_items', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', name='itinerarystatus'),
               nullable=True)
    op.alter_column('itinerary_items', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Meeting notes, purpose, special requirements',
               existing_nullable=True)
    op.drop_index(op.f('ix_itinerary_items_appointment_time'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_status'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_supplier_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_visit_id'), table_name='itinerary_items')
    op.drop_column('itinerary_items', 'updated_at')
    op.drop_column('itinerary_items', 'created_at')
    op.alter_column('transports', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transports', 'visit_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transports', 'driver_details',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Driver name, contact, vehicle details',
               existing_nullable=True)
    op.alter_column('transports', 'time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Scheduled pickup/drop time',
               existing_nullable=False)
    op.drop_index(op.f('ix_transports_id'), table_name='transports')
    op.drop_index(op.f('ix_transports_mode'), table_name='transports')
    op.drop_index(op.f('ix_transports_type'), table_name='transports')
    op.drop_index(op.f('ix_transports_visit_id'), table_name='transports')
    op.drop_column('transports', 'updated_at')
    op.drop_column('transports', 'created_at')
    op.alter_column('visits', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Visit start date and time',
               existing_nullable=False)
    op.alter_column('visits', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Visit end date and time',
               existing_nullable=False)
    op.alter_column('visits', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'ONGOING', 'COMPLETED', 'CANCELLED', name='visitstatus'),
               nullable=True)
    op.alter_column('visits', 'visit_mode',
               existing_type=postgresql.ENUM('ACCOMPANIED', 'SOLO', name='visitmode'),
               nullable=True)
    op.alter_column('visits', 'arrival_details',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Flight/train details, arrival time, etc.',
               existing_nullable=True)
    op.alter_column('visits', 'ticket_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL to ticket/booking confirmation',
               existing_nullable=True)
    op.drop_index(op.f('ix_visits_customer_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_end_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_salesperson_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_start_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_status'), table_name='visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_visits_status'), 'visits', ['status'], unique=False)
    op.create_index(op.f('ix_visits_start_date'), 'visits', ['start_date'], unique=False)
    op.create_index(op.f('ix_visits_salesperson_id'), 'visits', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_end_date'), 'visits', ['end_date'], unique=False)
    op.create_index(op.f('ix_visits_customer_id'), 'visits', ['customer_id'], unique=False)
    op.alter_column('visits', 'ticket_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL to ticket/booking confirmation',
               existing_nullable=True)
    op.alter_column('visits', 'arrival_details',
               existing_type=sa.TEXT(),
               comment='Flight/train details, arrival time, etc.',
               existing_nullable=True)
    op.alter_column('visits', 'visit_mode',
               existing_type=postgresql.ENUM('ACCOMPANIED', 'SOLO', name='visitmode'),
               nullable=False)
    op.alter_column('visits', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'ONGOING', 'COMPLETED', 'CANCELLED', name='visitstatus'),
               nullable=False)
    op.alter_column('visits', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Visit end date and time',
               existing_nullable=False)
    op.alter_column('visits', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Visit start date and time',
               existing_nullable=False)
    op.add_column('transports', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('transports', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_transports_visit_id'), 'transports', ['visit_id'], unique=False)
    op.create_index(op.f('ix_transports_type'), 'transports', ['type'], unique=False)
    op.create_index(op.f('ix_transports_mode'), 'transports', ['mode'], unique=False)
    op.create_index(op.f('ix_transports_id'), 'transports', ['id'], unique=False)
    op.alter_column('transports', 'time',
               existing_type=postgresql.TIMESTAMP(),
               comment='Scheduled pickup/drop time',
               existing_nullable=False)
    op.alter_column('transports', 'driver_details',
               existing_type=sa.VARCHAR(length=200),
               comment='Driver name, contact, vehicle details',
               existing_nullable=True)
    op.alter_column('transports', 'visit_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('transports', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('itinerary_items', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('itinerary_items', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_itinerary_items_visit_id'), 'itinerary_items', ['visit_id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_supplier_id'), 'itinerary_items', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_status'), 'itinerary_items', ['status'], unique=False)
    op.create_index(op.f('ix_itinerary_items_id'), 'itinerary_items', ['id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_appointment_time'), 'itinerary_items', ['appointment_time'], unique=False)
    op.alter_column('itinerary_items', 'notes',
               existing_type=sa.TEXT(),
               comment='Meeting notes, purpose, special requirements',
               existing_nullable=True)
    op.alter_column('itinerary_items', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', name='itinerarystatus'),
               type_=postgresql.ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'),
               nullable=False)
    op.alter_column('itinerary_items', 'appointment_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='Scheduled appointment time',
               existing_nullable=False)
    op.alter_column('itinerary_items', 'supplier_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('itinerary_items', 'visit_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('itinerary_items', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('accommodations', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('accommodations', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_accommodations_visit_id'), 'accommodations', ['visit_id'], unique=False)
    op.create_index(op.f('ix_accommodations_type'), 'accommodations', ['type'], unique=False)
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.alter_column('accommodations', 'bed_assigned',
               existing_type=sa.INTEGER(),
               comment='Bed number (1-5) for office guest house',
               existing_nullable=True)
    op.alter_column('accommodations', 'details',
               existing_type=sa.TEXT(),
               comment='Hotel name, address, or guest house details',
               existing_nullable=True)
    op.alter_column('accommodations', 'visit_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('accommodations', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
