"""Add Product and JSONB Variants

Revision ID: 6d97f922cd61
Revises: ac6860db1838
Create Date: 2026-01-24 11:53:54.828168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d97f922cd61'
down_revision: Union[str, Sequence[str], None] = 'ac6860db1838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Product name (e.g., 'Banarasi Saree Design 101')"),
    sa.Column('base_price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Base price before variant adjustments'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed product description'),
    sa.Column('category', sa.String(length=100), nullable=False, comment="Product category (e.g., 'Sarees', 'Suits')"),
    sa.Column('workflow_stage', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='workflowstage', create_type=False), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False, comment='Stock Keeping Unit - unique identifier'),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Flexible attributes: {"Color": "Red", "Fabric": "Silk", "Size": "Free"}'),
    sa.Column('price_adjustment', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Price adjustment from base price (can be positive or negative)'),
    sa.Column('stock_quantity', sa.Integer(), nullable=False, comment='Current stock quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attributes', name='uq_product_variant_attributes')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.drop_constraint(op.f('partners_gst_number_key'), 'partners', type_='unique')
    op.drop_index(op.f('ix_partners_gst_number'), table_name='partners')
    op.create_index(op.f('ix_partners_gst_number'), 'partners', ['gst_number'], unique=True)
    op.drop_constraint(op.f('partners_created_by_id_fkey'), 'partners', type_='foreignkey')
    op.drop_column('partners', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('partners_created_by_id_fkey'), 'partners', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_partners_gst_number'), table_name='partners')
    op.create_index(op.f('ix_partners_gst_number'), 'partners', ['gst_number'], unique=False)
    op.create_unique_constraint(op.f('partners_gst_number_key'), 'partners', ['gst_number'])
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
