"""Add Project Namaste models - Visit, Accommodation, Transport, ItineraryItem

Revision ID: 73c83786a214
Revises: simple_orders
Create Date: 2026-01-24 17:18:32.408045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73c83786a214'
down_revision: Union[str, Sequence[str], None] = 'simple_orders'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('salesperson_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='Visit start date and time'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='Visit end date and time'),
    sa.Column('status', sa.Enum('SCHEDULED', 'ONGOING', 'COMPLETED', 'CANCELLED', name='visitstatus'), nullable=False),
    sa.Column('visit_mode', sa.Enum('ACCOMPANIED', 'SOLO', name='visitmode'), nullable=False),
    sa.Column('arrival_details', sa.Text(), nullable=True, comment='Flight/train details, arrival time, etc.'),
    sa.Column('ticket_url', sa.String(length=500), nullable=True, comment='URL to ticket/booking confirmation'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workflow_stage', postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='workflowstage', create_type=False), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['salesperson_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_customer_id'), 'visits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_visits_end_date'), 'visits', ['end_date'], unique=False)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_salesperson_id'), 'visits', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_visits_start_date'), 'visits', ['start_date'], unique=False)
    op.create_index(op.f('ix_visits_status'), 'visits', ['status'], unique=False)
    op.create_table('accommodations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('OFFICE_GUEST_HOUSE', 'HOTEL', 'SELF', name='accommodationtype'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True, comment='Hotel name, address, or guest house details'),
    sa.Column('bed_assigned', sa.Integer(), nullable=True, comment='Bed number (1-5) for office guest house'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.create_index(op.f('ix_accommodations_type'), 'accommodations', ['type'], unique=False)
    op.create_index(op.f('ix_accommodations_visit_id'), 'accommodations', ['visit_id'], unique=False)
    op.create_table('itinerary_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('appointment_time', sa.DateTime(), nullable=False, comment='Scheduled appointment time'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='Meeting notes, purpose, special requirements'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_items_appointment_time'), 'itinerary_items', ['appointment_time'], unique=False)
    op.create_index(op.f('ix_itinerary_items_id'), 'itinerary_items', ['id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_status'), 'itinerary_items', ['status'], unique=False)
    op.create_index(op.f('ix_itinerary_items_supplier_id'), 'itinerary_items', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_visit_id'), 'itinerary_items', ['visit_id'], unique=False)
    op.create_table('transports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PICKUP', 'DROP', 'MARKET_TOUR', name='transporttype'), nullable=False),
    sa.Column('mode', sa.Enum('COMPANY_DRIVER', 'TAXI', 'AUTO', 'SELF', name='transportmode'), nullable=False),
    sa.Column('driver_details', sa.String(length=200), nullable=True, comment='Driver name, contact, vehicle details'),
    sa.Column('time', sa.DateTime(), nullable=False, comment='Scheduled pickup/drop time'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transports_id'), 'transports', ['id'], unique=False)
    op.create_index(op.f('ix_transports_mode'), 'transports', ['mode'], unique=False)
    op.create_index(op.f('ix_transports_type'), 'transports', ['type'], unique=False)
    op.create_index(op.f('ix_transports_visit_id'), 'transports', ['visit_id'], unique=False)
    op.alter_column('approval_policies', 'resource',
               existing_type=sa.VARCHAR(length=50),
               comment="Resource type (e.g., 'partner', 'order')",
               existing_nullable=False)
    op.alter_column('approval_policies', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment="Action type (e.g., 'create', 'update', 'delete')",
               existing_nullable=False)
    op.alter_column('approval_policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this policy is active',
               existing_nullable=False)
    op.alter_column('approval_policies', 'required_role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'ACCOUNTANT', 'SALESMAN', name='userrole'),
               comment='Minimum role required for approval',
               existing_nullable=False)
    op.drop_constraint(op.f('orders_order_number_key'), 'orders', type_='unique')
    op.drop_constraint(op.f('partners_gst_number_key'), 'partners', type_='unique')
    op.drop_index(op.f('ix_partners_gst_number'), table_name='partners')
    op.create_index(op.f('ix_partners_gst_number'), 'partners', ['gst_number'], unique=True)
    op.drop_constraint(op.f('partners_created_by_id_fkey'), 'partners', type_='foreignkey')
    op.drop_column('partners', 'created_by_id')
    op.alter_column('product_variants', 'sku',
               existing_type=sa.VARCHAR(length=100),
               comment='Stock Keeping Unit - unique identifier',
               existing_nullable=False)
    op.alter_column('product_variants', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Flexible attributes: {"Color": "Red", "Fabric": "Silk", "Size": "Free"}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('product_variants', 'price_adjustment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Price adjustment from base price (can be positive or negative)',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('product_variants', 'stock_quantity',
               existing_type=sa.INTEGER(),
               comment='Current stock quantity',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('product_variants_sku_key'), 'product_variants', type_='unique')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment="Product name (e.g., 'Banarasi Saree Design 101')",
               existing_nullable=False)
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Base price before variant adjustments',
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment='Detailed product description',
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment="Product category (e.g., 'Sarees', 'Suits')",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Product category (e.g., 'Sarees', 'Suits')",
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed product description',
               existing_nullable=True)
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Base price before variant adjustments',
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Product name (e.g., 'Banarasi Saree Design 101')",
               existing_nullable=False)
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.create_unique_constraint(op.f('product_variants_sku_key'), 'product_variants', ['sku'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_variants', 'stock_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Current stock quantity',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_variants', 'price_adjustment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Price adjustment from base price (can be positive or negative)',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('product_variants', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Flexible attributes: {"Color": "Red", "Fabric": "Silk", "Size": "Free"}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('product_variants', 'sku',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Stock Keeping Unit - unique identifier',
               existing_nullable=False)
    op.add_column('partners', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('partners_created_by_id_fkey'), 'partners', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_partners_gst_number'), table_name='partners')
    op.create_index(op.f('ix_partners_gst_number'), 'partners', ['gst_number'], unique=False)
    op.create_unique_constraint(op.f('partners_gst_number_key'), 'partners', ['gst_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('orders_order_number_key'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('approval_policies', 'required_role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'ACCOUNTANT', 'SALESMAN', name='userrole'),
               comment=None,
               existing_comment='Minimum role required for approval',
               existing_nullable=False)
    op.alter_column('approval_policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this policy is active',
               existing_nullable=False)
    op.alter_column('approval_policies', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Action type (e.g., 'create', 'update', 'delete')",
               existing_nullable=False)
    op.alter_column('approval_policies', 'resource',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Resource type (e.g., 'partner', 'order')",
               existing_nullable=False)
    op.drop_index(op.f('ix_transports_visit_id'), table_name='transports')
    op.drop_index(op.f('ix_transports_type'), table_name='transports')
    op.drop_index(op.f('ix_transports_mode'), table_name='transports')
    op.drop_index(op.f('ix_transports_id'), table_name='transports')
    op.drop_table('transports')
    op.drop_index(op.f('ix_itinerary_items_visit_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_supplier_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_status'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_appointment_time'), table_name='itinerary_items')
    op.drop_table('itinerary_items')
    op.drop_index(op.f('ix_accommodations_visit_id'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_type'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_table('accommodations')
    op.drop_index(op.f('ix_visits_status'), table_name='visits')
    op.drop_index(op.f('ix_visits_start_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_salesperson_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_end_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_customer_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
