"""add staging_entries

Revision ID: a3517b917cfd
Revises: 015d16e81935
Create Date: 2026-01-30 13:51:34.401482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3517b917cfd'
down_revision: Union[str, Sequence[str], None] = '015d16e81935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_phone', sa.String(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('detected_type', sa.Enum('INVOICE', 'ORDER_FORM', 'LR', 'TRAVEL_TICKET', 'PAYMENT_RECEIPT', 'UNKNOWN', name='documenttype'), nullable=True),
    sa.Column('ai_extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', name='processingstatus'), nullable=True),
    sa.Column('manager_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staging_entries')
    # ### end Alembic commands ###
